baseURL = 'https://k.ior.works/'
languageCode = 'en-us'
title = 'TAN SAN'
theme = 'LoveIt'
enableRobotsTXT = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[output]
  home = ["HTML", "RSS", "JSON"]
[params]
  description = "Spill your cola."
  [params.home]
    [params.home.profile]
      description = "bang"